json.id @article.id
json.title @article.title
json.body @article.body
json.author @article.user
json.draft @article.draft
json.batch_number @article.batch_number
json.category @article.article_category
json.resource @article.resource
json.comments @comments
json.created_at @article.created_at
json.updated_at @article.updated_at